#if !defined(AFX_SLIDER_H__27CAC0E3_EC26_450B_844E_FB99D984AA59__INCLUDED_)
#define AFX_SLIDER_H__27CAC0E3_EC26_450B_844E_FB99D984AA59__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CSlider wrapper class

class CSlider : public CWnd
{
protected:
    DECLARE_DYNCREATE(CSlider)
public:
    CLSID const& GetClsid()
    {
        static CLSID const clsid
            = { 0x373ff7f0, 0xeb8b, 0x11cd, { 0x88, 0x20, 0x8, 0x0, 0x2b, 0x2f, 0x4f, 0x5a } };
        return clsid;
    }
    virtual BOOL Create(LPCTSTR lpszClassName,
        LPCTSTR lpszWindowName, DWORD dwStyle,
        const RECT& rect,
        CWnd* pParentWnd, UINT nID,
        CCreateContext* pContext = NULL)
    { return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
        const RECT& rect, CWnd* pParentWnd, UINT nID,
        CFile* pPersist = NULL, BOOL bStorage = FALSE,
        BSTR bstrLicKey = NULL)
    { return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
        pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
    long GetLargeChange();
    void SetLargeChange(long nNewValue);
    long GetSmallChange();
    void SetSmallChange(long nNewValue);
    long GetMax();
    void SetMax(long nNewValue);
    long GetMin();
    void SetMin(long nNewValue);
    long GetOrientation();
    void SetOrientation(long nNewValue);
    BOOL GetSelectRange();
    void SetSelectRange(BOOL bNewValue);
    long GetSelStart();
    void SetSelStart(long nNewValue);
    long GetSelLength();
    void SetSelLength(long nNewValue);
    long GetTickStyle();
    void SetTickStyle(long nNewValue);
    long GetTickFrequency();
    void SetTickFrequency(long nNewValue);
    long GetValue();
    void SetValue(long nNewValue);
    CPicture GetMouseIcon();
    void SetMouseIcon(LPDISPATCH newValue);
    void SetRefMouseIcon(LPDISPATCH newValue);
    long GetMousePointer();
    void SetMousePointer(long nNewValue);
    BOOL GetEnabled();
    void SetEnabled(BOOL bNewValue);
    long GetHWnd();
    void SetHWnd(long nNewValue);
    long GetBorderStyle();
    void SetBorderStyle(long nNewValue);
    long GetOLEDropMode();
    void SetOLEDropMode(long nNewValue);
    void Refresh();
    void ClearSel();
    long GetGetNumTicks();
    void OLEDrag();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SLIDER_H__27CAC0E3_EC26_450B_844E_FB99D984AA59__INCLUDED_)
